"""Plan de cuentas base para una empresa chilena.

Cada entrada es (código, nombre, imputable). El tipo de cuenta se deduce del
primer dígito del código. Las cuentas no imputables son grupos (títulos) que
agrupan a las cuentas cuyo código comienza con el suyo.
"""

TIPO_POR_DIGITO = {
    "1": "ACTIVO",
    "2": "PASIVO",
    "3": "PATRIMONIO",
    "4": "INGRESO",
    "5": "GASTO",
}

PLAN_CUENTAS = [
    ("1", "ACTIVO", False),
    ("1.1", "ACTIVO CIRCULANTE", False),
    ("1.1.01", "Caja", True),
    ("1.1.02", "Banco", True),
    ("1.1.03", "Depósitos a plazo", True),
    ("1.1.04", "Clientes", True),
    ("1.1.05", "Documentos por cobrar", True),
    ("1.1.06", "Deudores varios", True),
    ("1.1.07", "Provisión deudores incobrables", True),
    ("1.1.08", "Mercaderías", True),
    ("1.1.09", "IVA crédito fiscal", True),
    ("1.1.10", "Pagos provisionales mensuales (PPM)", True),
    ("1.1.11", "Anticipo a proveedores", True),
    ("1.2", "ACTIVO FIJO", False),
    ("1.2.01", "Terrenos", True),
    ("1.2.02", "Construcciones", True),
    ("1.2.03", "Maquinarias y equipos", True),
    ("1.2.04", "Vehículos", True),
    ("1.2.05", "Muebles y útiles", True),
    ("1.2.06", "Equipos computacionales", True),
    ("1.2.07", "Depreciación acumulada", True),
    ("1.3", "OTROS ACTIVOS", False),
    ("1.3.01", "Garantías entregadas", True),
    ("1.3.02", "Intangibles", True),
    ("2", "PASIVO", False),
    ("2.1", "PASIVO CIRCULANTE", False),
    ("2.1.01", "Proveedores", True),
    ("2.1.02", "Documentos por pagar", True),
    ("2.1.03", "Acreedores varios", True),
    ("2.1.04", "IVA débito fiscal", True),
    ("2.1.05", "Impuesto único por pagar", True),
    ("2.1.06", "Retención de honorarios por pagar", True),
    ("2.1.07", "PPM por pagar", True),
    ("2.1.08", "Remuneraciones por pagar", True),
    ("2.1.09", "Cotizaciones previsionales por pagar", True),
    ("2.1.10", "Impuesto a la renta por pagar", True),
    ("2.1.11", "Préstamos bancarios de corto plazo", True),
    ("2.1.12", "Anticipo de clientes", True),
    ("2.2", "PASIVO DE LARGO PLAZO", False),
    ("2.2.01", "Préstamos bancarios de largo plazo", True),
    ("2.2.02", "Obligaciones por leasing", True),
    ("3", "PATRIMONIO", False),
    ("3.1", "CAPITAL Y RESERVAS", False),
    ("3.1.01", "Capital", True),
    ("3.1.02", "Utilidades retenidas", True),
    ("3.1.03", "Pérdidas acumuladas", True),
    ("3.1.04", "Resultado del ejercicio", True),
    ("3.1.05", "Retiros de socios", True),
    ("4", "INGRESOS", False),
    ("4.1", "INGRESOS DE EXPLOTACIÓN", False),
    ("4.1.01", "Ventas", True),
    ("4.1.02", "Ingresos por servicios", True),
    ("4.2", "INGRESOS NO OPERACIONALES", False),
    ("4.2.01", "Intereses ganados", True),
    ("4.2.02", "Otros ingresos", True),
    ("5", "GASTOS", False),
    ("5.1", "COSTOS DE EXPLOTACIÓN", False),
    ("5.1.01", "Costo de ventas", True),
    ("5.2", "GASTOS DE ADMINISTRACIÓN Y VENTAS", False),
    ("5.2.01", "Remuneraciones", True),
    ("5.2.02", "Leyes sociales (aporte patronal)", True),
    ("5.2.03", "Honorarios", True),
    ("5.2.04", "Arriendos", True),
    ("5.2.05", "Servicios básicos", True),
    ("5.2.06", "Gastos de oficina", True),
    ("5.2.07", "Publicidad", True),
    ("5.2.08", "Mantención y reparaciones", True),
    ("5.2.09", "Seguros", True),
    ("5.2.10", "Depreciación del ejercicio", True),
    ("5.2.11", "Patentes y contribuciones", True),
    ("5.2.12", "Gastos generales", True),
    ("5.3", "GASTOS NO OPERACIONALES", False),
    ("5.3.01", "Intereses y gastos bancarios", True),
    ("5.3.02", "Multas e intereses fiscales", True),
    ("5.3.03", "Otros gastos", True),
    ("5.4", "IMPUESTO A LA RENTA", False),
    ("5.4.01", "Impuesto a la renta de primera categoría", True),
]

# Cuenta de patrimonio a la que se traspasa el resultado en el cierre.
CODIGO_RESULTADO_EJERCICIO = "3.1.04"
